/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_sun_misc_Unsafe
#define _Included_sun_misc_Unsafe

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_objectFieldOffset(JNIEnv*, jobject, jobject);
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapInt(JNIEnv*, jobject, jobject, jlong, jint, jint);
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapLong(JNIEnv*, jobject, jobject, jlong, jlong, jlong);
JNIEXPORT jboolean JNICALL Java_sun_misc_Unsafe_compareAndSwapObject(JNIEnv*, jobject, jobject, jlong, jobject, jobject);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedInt(JNIEnv*, jobject, jobject, jlong, jint);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedLong(JNIEnv*, jobject, jobject, jlong, jlong);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putOrderedObject(JNIEnv*, jobject, jobject, jlong, jobject);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putIntVolatile(JNIEnv*, jobject, jobject, jlong, jint);
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_getIntVolatile(JNIEnv*, jobject, jobject, jlong);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putLongVolatile(JNIEnv*, jobject, jobject, jlong, jlong);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putLong(JNIEnv*, jobject, jobject, jlong, jlong);
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getLongVolatile(JNIEnv*, jobject, jobject, jlong);
JNIEXPORT jlong JNICALL Java_sun_misc_Unsafe_getLong(JNIEnv*, jobject, jobject, jlong);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putObjectVolatile(JNIEnv*, jobject, jobject, jlong, jobject);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_putObject(JNIEnv*, jobject, jobject, jlong, jobject);
JNIEXPORT jobject JNICALL Java_sun_misc_Unsafe_getObjectVolatile(JNIEnv*, jobject, jobject, jlong);
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_arrayBaseOffset(JNIEnv*, jobject, jclass);
JNIEXPORT jint JNICALL Java_sun_misc_Unsafe_arrayIndexScale(JNIEnv*, jobject, jclass);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_unpark(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_sun_misc_Unsafe_park(JNIEnv*, jobject, jboolean, jlong);

#ifdef __cplusplus
}
#endif

#endif
